DROP TABLE IF EXISTS `bbs_pointsave`;
CREATE TABLE IF NOT EXISTS `bbs_pointsave` (
`TpId` INT NOT NULL AUTO_INCREMENT ,
`name` VARCHAR( 45 ) NOT NULL ,
`charId` INT( 11 ) NOT NULL DEFAULT  '0',
`xPos` INT( 9 ) NOT NULL DEFAULT  '0',
`yPos` INT( 9 ) NOT NULL DEFAULT  '0',
`zPos` INT( 9 ) NOT NULL DEFAULT  '0',
PRIMARY KEY (  `TpId` )
) ENGINE = MYISAM DEFAULT CHARSET=utf8;