CREATE TABLE IF NOT EXISTS `cursed_weapons` (
	`item_id` SMALLINT UNSIGNED NOT NULL,
	`player_id` INT UNSIGNED NOT NULL DEFAULT '0',
	`player_karma` INT UNSIGNED NOT NULL DEFAULT '0',
	`player_pkkills` INT UNSIGNED NOT NULL DEFAULT '0',
	`nb_kills` INT UNSIGNED NOT NULL DEFAULT '0',
	`x` INT NOT NULL DEFAULT '0',
	`y` INT NOT NULL DEFAULT '0',
	`z` INT NOT NULL DEFAULT '0',
	`end_time` INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`item_id`)
) ENGINE=MyISAM;

